// apps/web/app/explorer/[chain]/txs/[hash]/page.tsx
import { Hash } from "@laceanatomy/types";
import CopyButton from "~/app/_components/ExplorerSection/CopyButton";
import TxTabs from "~/app/_components/ExplorerSection/Transactions/TxTabs";
import { Header } from "~/app/_components/Header";
import { type ChainNetwork, isValidChain } from "~/server/api/dbsync-provider";
import { loadPageData } from "./_utils";

interface Props {
  params: { chain: string; hash: string };
  searchParams?: { tab?: string };
}

const TABS = [
  "Overview",
  "Diagram",
  "Dissect",
  "CBOR",
  "Datum",
  "Scripts",
] as const;
type TxTab = (typeof TABS)[number];

function resolveTab(tab?: string): TxTab {
  if (!tab) return "Overview";
  const normalized = tab.toLowerCase();
  const match = TABS.find(
    (candidate) => candidate.toLowerCase() === normalized,
  );
  return match ?? "Overview";
}

export default async function TxPage({ params, searchParams }: Props) {
  const hash = params.hash;
  const chainParam = params.chain || "mainnet";
  const chain: ChainNetwork = isValidChain(chainParam) ? chainParam : "mainnet";
  const tabParam = searchParams?.tab;
  const tab = resolveTab(tabParam);

  try {
    const { cardanoTx, cbor, tx } = await loadPageData({
      chain,
      hash: Hash(hash),
    });
    return (
      <div className="flex min-h-screen flex-col bg-white">
        <Header />
        <main className="container mx-auto flex min-h-0 flex-1 flex-col px-4 py-6">
          <div className="mb-4 flex flex-shrink-0 items-center justify-between">
            <h1 className="text-3xl font-extrabold">{hash}</h1>
            <div className="flex items-center gap-2">
              <CopyButton text={hash} size={16} />
            </div>
          </div>
          <div className="flex min-h-0 flex-1">
            <TxTabs cardanoTx={cardanoTx} cbor={cbor} tx={tx} tab={tab} />
          </div>
        </main>
      </div>
    );
  } catch (err) {
    console.error(err);
    return (
      <div className="flex min-h-screen flex-col bg-white">
        <Header />
        <main className="container mx-auto flex flex-1 flex-col px-4 py-6">
          <div className="rounded-lg border-2 border-dashed border-gray-200 p-8 text-center text-gray-600">
            Transaction not found or could not be loaded.
          </div>
        </main>
      </div>
    );
  }
}

// apps/web/src/routes/tx/[hash]/+page.svelte
<script lang="ts">
  import { page } from '$app/stores';
  import { createProviderClient } from '@/client/provider-loader';
  import Cbor from '@/components/custom/cbor.svelte';
  import Datum from '@/components/custom/datum.svelte';
  import Diagram from '@/components/custom/diagram/diagram.svelte';
  import Dissect from '@/components/custom/dissect.svelte';
  import Overview from '@/components/custom/overview.svelte';
  import Scripts from '@/components/custom/scripts.svelte';
  import { Button } from '@/components/ui/button';
  import { Card, CardContent } from '@/components/ui/card';
  import { currentProvider } from '@/stores/provider-store';
  import type { CardanoTx } from '@alexandria/types';
  import type { ProviderConfig } from '@/client';

  interface Props {
    data: {
      tx: CardanoTx | null;
      cbor: string | null;
      isServerLoaded: boolean;
      error?: string;
      datumTab?: string;
    };
  }

  let { data }: Props = $props();

  // client states
  let clientTx = $state<CardanoTx | null>(null);
  let clientLoading = $state(false);
  let clientError = $state<string | null>(null);

  // Tabs
  type TabKey = 'Overview' | 'Diagram' | 'Dissect' | 'CBOR' | 'Datum' | 'Scripts';
  const tabs = ['Overview', 'Diagram', 'Dissect', 'CBOR', 'Datum', 'Scripts'] as const;

  let activeTab = $derived<TabKey>(data.datumTab ? 'Datum' : 'Overview');
  let cbor = $derived<string>(data.cbor ?? '');

  $effect(() => {
    if (!data.isServerLoaded && $currentProvider && $currentProvider.isLocal) {
      clientLoading = true;
      clientError = null;

      loadCustomProviderData($currentProvider)
        .catch((error) => {
          console.error(error);
          clientError = error instanceof Error ? error.message : 'Unknown error loading tx';
        })
        .finally(() => {
          clientLoading = false;
        });
    }
  });

  async function loadCustomProviderData(provider: ProviderConfig) {
    const client = createProviderClient(provider);
    const hash = $page.params.hash as unknown as import('@alexandria/types').Hash;
    clientTx = await client.getTx({ hash });
    try {
      cbor = await client.getCBOR({ hash });
    } catch {
      console.error('CBOR not available');
    }
  }

  const displayTx = $derived(data.isServerLoaded ? data.tx : clientTx);
</script>

<div class="container mx-auto space-y-6 px-4 py-3">
  <div class="flex items-center justify-between">
    <h1 class="text-3xl font-extrabold">{$page.params.hash}</h1>
  </div>

  {#if clientLoading}
    <Card>
      <CardContent class="py-8 text-center">
        <div class="flex items-center justify-center gap-2">
          <div class="border-primary h-6 w-6 animate-spin rounded-full border-b-2"></div>
          <span class="text-muted-foreground">Loading transaction from custom provider...</span>
        </div>
      </CardContent>
    </Card>
  {:else if displayTx}
    <!-- Tabs header -->
    <div class="flex gap-2 border-b pb-2">
      {#each tabs as tab (tab)}
        <Button
          size="sm"
          variant={activeTab === tab ? 'default' : 'outline'}
          onclick={() => (activeTab = tab)}>{tab.charAt(0).toUpperCase() + tab.slice(1)}</Button
        >
      {/each}
    </div>

    {#if clientError}
      <div class="text-sm text-red-600">Client error: {clientError}</div>
    {/if}

    {#if activeTab === 'Overview'}
      <Overview {displayTx} />
    {/if}

    {#if activeTab === 'Diagram'}
      <Card class="z-0">
        <CardContent class="py-1">
          <Diagram tx={displayTx} />
        </CardContent>
      </Card>
    {/if}

    {#if activeTab === 'Dissect'}
      <Dissect tx={displayTx} />
    {/if}

    {#if activeTab === 'Datum'}
      <Datum tx={displayTx} tab={data.datumTab} />
    {/if}

    {#if activeTab === 'CBOR'}
      <Cbor {cbor} error={data.error} />
    {/if}

    {#if activeTab === 'Scripts'}
      <Scripts tx={displayTx} />
    {/if}
  {:else}
    <Card>
      <CardContent class="text-muted-foreground py-8 text-center">
        Transaction not found or not loaded.<br />
      </CardContent>
    </Card>
  {/if}
</div>

<style>
  /* minimal overrides if needed */
</style>
